import React, { useState } from 'react'
import ProjectItem from './ProjectItem'
import cars from "../public/Imgs/Group 30.png";
import chatGPT from "../public/Imgs/Group 29.jpg";
import ai from "../public/Imgs/Group 28.jpg";
import scrapbook from "../public/Imgs/Group 23.png";

const Project = () => {

    const [projectSelected, setProjectSelected] = useState("CarHub");

  return (
    <div className='project'>
        <h2>PROJECTS</h2>
        <h3 onClick={() => setProjectSelected("CarHub")}>CarHub</h3>
        <h3 onClick={() => setProjectSelected("chatGPT")}>Dall.E Image Generator</h3>
        <h3 onClick={() => setProjectSelected("AI")}>AI Chat App</h3>
        <h3 onClick={() => setProjectSelected("scrapbook")}>Scrapbook</h3>


        <div className="productDetails">
            {
                projectSelected === "CarHub" && <ProjectItem projectName=" CarHub"
                purpose=": Discover your ideal vehicle! Explore an extensive database equipped with autocomplete functionality to effortlessly locate your desired car. Enhance your search experience with advanced filters, increasing the likelihood of finding the exact car you're looking for. The front end of my application is crafted using Next.js, TypeScript, Headless UI, and Tailwind CSS, while seamlessly integrating with multiple APIs to fetch and populate the car data in the app." 
                techStack = {["Next js", "Typescript", "Headless UI", "APIs", "Tailwind CSS"]}
                sourceCode = "https://github.com/SanjeevMidda/car_web_app" image={cars}/>
            }
            {
                projectSelected === "chatGPT" && <ProjectItem projectName=" DALL.E Image Generator" purpose=": Harness the power of DALL.E to craft an exceptionally distinctive image. Users have the freedom to input their exact preferences or request a one-of-a-kind suggestion, allowing DALL.E to conjure up a unique visual masterpiece. The frontend of this application is developed using React and Tailwind CSS. Additionally, users have the ability to save any image generated by DALL.E for later viewing. The backend implementation relies on Node.js, Express, and MongoDB. Furthermore, Cloudinary is employed to optimize media retrieval for an enhanced user experience." techStack = {["react", "mongoDB", "node & express", "cloudinary", "openAI", "tailwind css"]} sourceCode = "https://github.com/SanjeevMidda/chatGPT-image-generator" image={chatGPT}/>
            }
            {
                projectSelected === "AI" && <ProjectItem projectName=" AI Chat App" purpose=": Unleash the boundless knowledge of the world at your fingertips! Empowered by AI technology, users can effortlessly pose any question, and our system will provide a distinct and insightful response. Seamlessly open multiple chats simultaneously and conveniently retrieve them at a later time. With this remarkable capability, you can engage in limitless conversations and access a wealth of information." techStack = {["react", "node & express", "openAI"]} sourceCode = "https://github.com/SanjeevMidda/chat" image={ai}/>
            }
            {
                projectSelected === "scrapbook" && <ProjectItem projectName=" Scrapbook" purpose=": Miscellaneous collection of projects" techStack = {["various"]} sourceCode = "https://github.com/SanjeevMidda/" image={scrapbook}/>
            }
        </div>
    </div>
  )
}

export default Project